name: GraalVM CI

on: [push]
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: |
        wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-darwin-amd64-20.0.0.tar.gz
        tar xzf graalvm-ce-java11-darwin-amd64-20.0.0.tar.gz
        export JAVA_HOME="$(pwd)/graalvm-ce-java11-20.0.0/Contents/Home/"
        ${JAVA_HOME}/bin/gu install native-image
        brew install upx
        ./mvnw --batch-mode package
        upx --brute target/graalfx-mac-*
        mkdir target/artifacts
        cp target/graalfx-* target/artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: graalfx artifacts from ${{runner.os}} build
        path: target/artifacts
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: |
        wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz
        tar xzf graalvm-ce-java11-linux-amd64-20.0.0.tar.gz
        export JAVA_HOME="$(pwd)/graalvm-ce-java11-20.0.0"
        ${JAVA_HOME}/bin/gu install native-image
        sudo apt-get install upx-ucl
        ./mvnw --batch-mode package
        upx --brute target/graalfx-linux-*
        mkdir target/artifacts
        cp target/graalfx-* target/artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: graalfx artifacts from ${{runner.os}} build
        path: target/artifacts
  windows:
    runs-on: windows-latest
    env:
      VCVARS_BAT: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
    steps:
    - uses: actions/checkout@v4
    - run: choco install graalvm --version=20.0.0 --no-progress
    - run: choco install upx --version=3.96 --no-progress
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: .m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      shell: cmd
      env:
        JAVA_HOME: C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0
      run: |
        call "%JAVA_HOME%\bin\gu" install native-image
        call "%VCVARS_BAT%"
        call .\mvnw --batch-mode --settings .\.mvn\github-actions-windows-maven-settings.xml package
        upx --brute target/graalfx-win-*
        mkdir target\artifacts
        copy target\graalfx-* target\artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: graalfx artifacts from ${{runner.os}} build
        path: target/artifacts
